apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-lib.names.fullname" (dict "ctx" $ "name" .Chart.Name) }}
  labels:
    {{- include "common-lib.labels.standard" (dict "ctx" $ "name" .Chart.Name) | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common-lib.labels.selector" (dict "ctx" $ "name" .Chart.Name) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "common-lib.labels.selector" (dict "ctx" $ "name" .Chart.Name) | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-appconfig: |
          {{ .Values.vault.template | trim | nindent 10 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-info.serviceAccountName" . }}
      {{- include "common-lib.security.context" .Values.podSecurityContext | nindent 6 }}
      containers:
      - name: {{ .Chart.Name }}
        {{- include "common-lib.security.context" .Values.securityContext | nindent 8 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "devops-info.fullname" . }}-secret
        {{- include "common-lib.resources" .Values.resources | nindent 8 }}
        {{- include "common-lib.probes.liveness" .Values.livenessProbe | nindent 8 }}
        {{- include "common-lib.probes.readiness" .Values.readinessProbe | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}